version: "3.8"

services:
  notes-backend:
    image: dlippo/devopscourse-notes-backend:${TAG}
    container_name: notes-backend
    ports:
      - '5001:5000'
  
  notes-frontend:
    image: dlippo/devopscourse-notes-frontend:${TAG}
    container_name: notes-frontend
    ports:
      - '3000:80'
    depends_on:
      - notes-backend
      